<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="stereo_test_mast">

  <xacro:property name="Camera01Name"       value="NavCamStereo" /> 
  <xacro:property name="Camera01UpdateRate" value="5" />
  <xacro:property name="camera_baseline"    value="0.30" />
  
  <xacro:property name="deg_to_rad"         value="0.0174533" />
  
  <xacro:macro name="stereo_mast" params="stereo_mast_parent_link mast_height hfov img_w img_h noise_stddev update_rate off_x off_y off_z">
  

  <link name="${Camera01Name}_mast_link">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${mast_height/2}"/>
      <geometry>
        <box size="0.05 0.05 ${mast_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${mast_height/2}"/>
      <geometry>
        <box size="0.05 0.05 ${mast_height}"/>
      </geometry>
      <material name="Grey"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${mast_height/2}"/>
      <mass value="0.2"/>
      <!-- inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/ -->
      <inertia
          ixx="${0.2 / 12.0 * (0.05*0.05 + mast_height*mast_height)}" ixy="0.0" ixz="0.0"
          iyy="${0.2 / 12.0 * (mast_height*mast_height + 0.05*0.05)}" iyz="0.0"
          izz="${0.2 / 12.0 * (0.05*0.05 + 0.05*0.05)}"/>
    </inertial>
  </link>
  <gazebo reference="${Camera01Name}_mast_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <joint name="${Camera01Name}_mast_joint" type="fixed">
    <parent link="${stereo_mast_parent_link}"/>
    <child link="${Camera01Name}_mast_link"/>
    <origin xyz="${off_x} ${off_y} ${off_z}" rpy="${pi} ${pi/2} 0" />
  </joint>

  <link name="${Camera01Name}_head_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
      <visual>
        <origin xyz="0 0 0"  rpy="0 0 0"/>
        <geometry>
          <box size="0.025 ${camera_baseline} 0.025"/>
        </geometry>
        <material name="Gold"/>
      </visual>
    <visual>
      <origin xyz="0 ${camera_baseline/2} 0"  rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="Gold"/>
    </visual>
    <visual>
      <origin xyz="0 -${camera_baseline/2} 0"  rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="Gold"/>
    </visual>
    <inertial>
      <mass value="0.05" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      <!-- inertia
          ixx="${mass / 12.0 * (depth*depth + height*height)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (depth*depth + width*width)}"/ -->

      <!-- inertia
          ixx="${0.05 / 12.0 * (0.1*0.1 + 0.1*0.1)}" ixy="0.0" ixz="0.0"
          iyy="${0.05 / 12.0 * (0.1*0.1 + camera_baseline*camera_baseline)}" iyz="0.0"
          izz="${0.05 / 12.0 * (0.1*0.1 + camera_baseline*camera_baseline)}"/-->
   </inertial>
  </link>
  
  <!-- example for stereo setup is here: -->
  <!-- https://bitbucket.org/osrf/drcsim/src/52a691b8956045442ef22ba0aaee4520716807ff/multisense_sl_description/urdf/multisense_sl.urdf?at=default#cl-200 -->
  <!-- https://bitbucket.org/osrf/drcsim/src/52a691b8956045442ef22ba0aaee4520716807ff/drcsim_gazebo/launch/atlas_bringup.launch?at=default#cl-38 -->
  
  <gazebo reference="${Camera01Name}Left_link"/>
  <link name="${Camera01Name}Left_link"/>
  <link name="${Camera01Name}Left_optical_frame"/>
  <joint name="leftCamera_joint" type="fixed">
    <origin xyz="0.0 ${camera_baseline/2} 0.0" rpy="0 0 0"/>
    <parent link="${Camera01Name}_head_link"/>
    <child link="${Camera01Name}Left_link"/>
  </joint>
  <joint name="leftCamera_optical_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-${pi/2.0} 0 -${pi/2.0}"/>
    <parent link="${Camera01Name}Left_link"/>
    <child link="${Camera01Name}Left_optical_frame"/>
  </joint>

  <gazebo reference="${Camera01Name}Right_link"/>
  <link name="${Camera01Name}Right_link"/>
  <link name="${Camera01Name}Right_optical_frame"/>
  <joint name="rightCamera_joint" type="fixed">
    <origin xyz="0.0 -${camera_baseline/2} 0.0" rpy="0 0 0"/>
    <parent link="${Camera01Name}_head_link"/>
    <child link="${Camera01Name}Right_link"/>
  </joint>
  <joint name="rightCamera_optical_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-${pi/2.0} 0 -${pi/2.0}"/>
    <parent link="${Camera01Name}Right_link"/>
    <child link="${Camera01Name}Right_optical_frame"/>
  </joint>

  
  <gazebo reference="${Camera01Name}Left_link">
    <material>Gazebo/Red</material>
    <sensor type="multicamera" name="${Camera01Name}">
      <update_rate>${update_rate}</update_rate>
      <always_on>0</always_on>
      <camera name="left">
        <horizontal_fov>${hfov*deg_to_rad}</horizontal_fov>
        <image>
          <width>${img_w}</width>
          <height>${img_h}</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.2</near>
          <far>50000</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>${noise_stddev}</stddev>
        </noise>
      </camera>

      <camera name="right">
        <pose>0 -${camera_baseline} 0 0 0 0</pose>
         <horizontal_fov>${hfov*deg_to_rad}</horizontal_fov>
        <image>
          <width>${img_w}</width>
          <height>${img_h}</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.2</near>
          <far>50000</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>${noise_stddev}</stddev>
        </noise>
      </camera>

      <plugin name="stereo_camera_controller" filename="libgazebo_ros_triggered_multicamera.so">
        <cameraName>${Camera01Name}</cameraName>
        <alwaysOn>true</alwaysOn>
        <triggerTopicName>image_trigger</triggerTopicName>
        <updateRate>0.0</updateRate>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>${Camera01Name}Left_optical_frame</frameName>
        <hackBaseline>${camera_baseline}</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>  
  
  <!-- "Center Camera" for "video" -->
  <gazebo reference="${Camera01Name}Center_link"/>
  <link name="${Camera01Name}Center_link"/>
  <link name="${Camera01Name}Center_optical_frame"/>
  <joint name="CenterCamera_joint" type="fixed">
    <origin xyz="0.025 0.0 0.0" rpy="0 0 0"/>
    <parent link="${Camera01Name}_head_link"/>
    <child link="${Camera01Name}Center_link"/>
  </joint>
  <joint name="CenterCamera_optical_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-${pi/2.0} 0 -${pi/2.0}"/>
    <parent link="${Camera01Name}Center_link"/>
    <child link="${Camera01Name}Center_optical_frame"/>
  </joint>
  
  <gazebo reference="${Camera01Name}Center_link">
    <material>Gazebo/Blue</material>
    <sensor type="camera" name="${Camera01Name}Video">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>1.0</near>
          <far>10000</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>

      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>${Camera01Name}Video</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>  
  
  <!-- Camera Joint -->
  <joint name="${Camera01Name}_camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <parent link="${Camera01Name}_mast_link"/>
    <child link="${Camera01Name}_head_link"/>
  </joint>

  </xacro:macro>
</robot>
